# spikeness theme v 0.1 for slim
# by tablet mode
# based on Robert Führicht's Gentoo theme for slim

# Messages (ie: shutdown)
msg_color               #d1dfad
msg_font                Sans:size=16:bold
msg_shadow_xoffset 	0
msg_shadow_yoffset 	0
msg_shadow_color   	#aaaaaa

# Screen background style. Valid values: stretch, tile
background_style        stretch

# Input controls
input_panel_x           50%
input_panel_y           61%

input_name_x            32 
input_name_y            64

input_pass_x            32 
input_pass_y            134

input_font          	Sans:size=13:bold
input_color           	#d1dfad
input_shadow_xoffset 	0
input_shadow_yoffset 	0
input_shadow_color   	#666666
