# curiosity theme v 0.1 for slim
# by tablet mode
# based on Robert Führicht's Gentoo theme for slim

# Messages (ie: shutdown)
msg_color               #ff2a7f
msg_font                Sans:size=16:bold
msg_shadow_xoffset 	0
msg_shadow_yoffset 	0
msg_shadow_color   	#aaaaaa

# Screen background style. Valid values: stretch, tile
background_style        stretch

# Input controls
input_panel_x           50%
input_panel_y           70%

input_name_x            40 
input_name_y            68 

input_pass_x            40 
input_pass_y            124

input_font          	Sans:size=13:bold
input_color           	#ff2a7f
input_shadow_xoffset 	0
input_shadow_yoffset 	0
input_shadow_color   	#666666



# Welcome message
#welcome_font          	Sans:size=18:bold:dpi=96
#welcome_color          	#333333
#welcome_x              	12
#welcome_y              	0
#welcome_msg		welcome to %host
#welcome_msg             welcome!
#welcome_shadow_xoffset 	0
#welcome_shadow_yoffset 	0
#welcome_shadow_color   	#898989


#username_msg            Username:
#username_font           Sans:size=14:bold:dpi=96
#username_color		    #3771c8f
#username_x              22
#username_y              60
#username_shadow_xoffset 0
#username_shadow_yoffset 0
#username_shadow_color   #666666

#password_msg		Password:
#password_x              22
#password_y              106
