# smile theme v 0.3 for slim
# by Tablet Mode
# based on Robert Führicht's Gentoo theme for slim

# Messages (ie: shutdown)
msg_color               #ff5599
msg_font                Sans:size=16:bold
msg_shadow_xoffset 	0
msg_shadow_yoffset 	0
msg_shadow_color   	#aaaaaa

# Screen background style. Valid values: stretch, tile
background_style        stretch

# Input controls
input_panel_x           49%
input_panel_y           75%
input_name_x            122
input_name_y            70
input_pass_x            122
input_pass_y            116

input_font          	Sans:size=12
input_color           	#ff5599
input_shadow_xoffset 	0
input_shadow_yoffset 	0
input_shadow_color   	#666666



# Welcome message
#welcome_font          	Sans:size=18:bold:dpi=96
#welcome_color          	#eeeeee
#welcome_x              	196
#welcome_y               4	
#welcome_msg		welcome to %host
#welcome_msg             :-D
#welcome_shadow_xoffset 	0
#welcome_shadow_yoffset 	0
#welcome_shadow_color   	#333333


#username_msg            Username:
#username_font           Sans:size=14:bold:dpi=96
#username_color		#f6b7d2
#username_x              22
#username_y              60
#username_shadow_xoffset 0
#username_shadow_yoffset 0
#username_shadow_color   #666666

#password_msg		Password:
#password_x              22
#password_y              106
